### ISSUE TITLE
tool keeps building up unfinished comparisons

### ISSUE THREAD

**Issue by SanVerhavert** [d-pac/d-pac.client#75] opened 2015-05-28 11:33 UTC
```json
{"now":"2015-05-28T11:26:53.953Z","url":"http://staging.tool.d-pac.be/assessors/#assess","version":"0.4.0 (659)","request":{"url":"/api/timelogs/5566fb79b4738fcd435a31d4","uuid":"3e75a6e2-f944-40e7-849c-9ae9cc7ed3bb"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"}
```
After clicking download button and back in browser several times the page says you  have three open comparisons (see screenshot in comment issue#74). After hitting continue comparisons and  finishing the last comparison the tool returns to the you have open comparisons page saying you have two open comparisons. When hitting continue comparisons you get a error (see schreenshot).

![image](https://cloud.githubusercontent.com/assets/9549353/7859093/09cc56ae-053e-11e5-81d3-3e49d1b3b718.png)

**Comment by creynders** [comment] 2015-05-29 11:43
Note to self: gut feeling; representations collection is cleared in between route completions, but comparisons collection is not.
![screen shot 2015-05-29 at 12 39 37](https://cloud.githubusercontent.com/assets/436347/7881911/6f5d3342-0608-11e5-95f1-c361686c4379.png)

**Comment by creynders** [comment] 2015-06-01 08:03
Hmmm very weird, I can't reproduce this anymore.

**Comment by creynders** [comment] 2015-06-02 09:09
Closing this for now, please reopen if you re-encounter this bug.

**Comment by creynders** [comment] 2015-06-02 09:25
Haha, somehow I managed to reproduce this, but I have no idea how. Anyway, still a valid bug.

**Closed** 2015-06-08 07:58 UTC
Labels: bug, confirmed
