### ISSUE TITLE
hitting return in comparative feedback and then "continue comparison" leads to error

### ISSUE THREAD

**Issue by SanVerhavert** [d-pac/d-pac.client#79] opened 2015-05-28 12:14 UTC
```json
{"now":"2015-05-28T12:05:07.370Z","url":"http://staging.tool.d-pac.be/assessors/#assess","version":"0.4.0 (659)","request":{"url":"/api/timelogs","uuid":"ed6723d3-072f-4b53-bf74-10549e52d395"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"}
```

When you hit return in the browser when you are on the comparative feedback screen (arriving at welcome screen 2 (see screenshot), then hit one of the judge buttons and then hit "continue comparison", there is an error.

Refreshing the page with "error..." and having to repeat the last two steps does not lead to an error.

![image](https://cloud.githubusercontent.com/assets/9549353/7859709/9ff1f936-0543-11e5-99db-ea08a0d666ce.png)

**Comment by creynders** [comment] 2015-05-29 08:55
I can't reproduce this issue.

**Comment by creynders** [comment] 2015-06-02 09:08
Closing this now, please reopen if you re-encounter this bug.

**Closed by creynders** 2015-06-02 09:08 UTC
Labels: cannot reproduce
